import type { NextPage } from "next";
import { useEffect, useState, KeyboardEvent } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { YouTubeEmbed } from "./YouTubeEmbed";
import { MediaButtons } from "./MediaButtons";

export const lofiIds = [
  "-5KAN9_CzSA",
  "jfKfPfyJRdk",
  "ceqgwo7U28Y",
  "rUxyKA_-grg",
  "qmI2YCrod00",
];

const Home: NextPage = () => {
  const [playing, setPlaying] = useState(false);
  const [volume, setVolume] = useState("60");
  const [currentTrack, setCurrentTrack] = useState(lofiIds[0]);

  useEffect(() => {
    function handleKeyDown(e: any): any {
      console.log(e.code);
      if (e.code === "Space") {
        e.preventDefault();
        setPlaying((prevProps) => !prevProps);
      }
    }

    document.addEventListener("keydown", handleKeyDown);

    return function cleanup() {
      document.removeEventListener("keydown", handleKeyDown);
    };
  }, [playing]);

  return (
    <div className={`${styles.container} bg-main-wall`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main}`}>
        <div className={styles.youtubePlayer}>
          <YouTubeEmbed videoId={currentTrack} play={playing} volume={volume} />
        </div>
        <div className={`flex-start`}>
          <h1 className={styles.title}>Lo-Fi Radio</h1>
        </div>

        <div className={styles.mediaPlayer}>
          <MediaButtons
            volume={volume}
            setVolume={setVolume}
            playing={playing}
            setPlaying={setPlaying}
            setCurrentTrack={setCurrentTrack}
          />
        </div>
      </main>
    </div>
  );
};

export default Home;
